// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY']!,
    appId: '1:961803445314:web:60cfcc7279f360507b79db',
    messagingSenderId: '961803445314',
    projectId: 'presence-app-9a958',
    authDomain: 'presence-app-9a958.firebaseapp.com',
    storageBucket: 'presence-app-9a958.firebasestorage.app',
    measurementId: 'G-VZFTQB5EYD',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY']!,
    appId: '1:961803445314:android:4251a81fca8dd1e67b79db',
    messagingSenderId: '961803445314',
    projectId: 'presence-app-9a958',
    storageBucket: 'presence-app-9a958.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    appId: '1:961803445314:ios:dd85c22b9b8ad2817b79db',
    messagingSenderId: '961803445314',
    projectId: 'presence-app-9a958',
    storageBucket: 'presence-app-9a958.firebasestorage.app',
    iosBundleId: 'com.rakafebriansy.presenceApp',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    appId: '1:961803445314:ios:dd85c22b9b8ad2817b79db',
    messagingSenderId: '961803445314',
    projectId: 'presence-app-9a958',
    storageBucket: 'presence-app-9a958.firebasestorage.app',
    iosBundleId: 'com.rakafebriansy.presenceApp',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY']!,
    appId: '1:961803445314:web:93b6fb9c615bf6937b79db',
    messagingSenderId: '961803445314',
    projectId: 'presence-app-9a958',
    authDomain: 'presence-app-9a958.firebaseapp.com',
    storageBucket: 'presence-app-9a958.firebasestorage.app',
    measurementId: 'G-0FW5Y3EETE',
  );
}