// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-zWDAntdsgS2H52W7TnGsGyg1CsvL0og',
    appId: '1:961803445314:web:60cfcc7279f360507b79db',
    messagingSenderId: '961803445314',
    projectId: 'presence-app-9a958',
    authDomain: 'presence-app-9a958.firebaseapp.com',
    storageBucket: 'presence-app-9a958.firebasestorage.app',
    measurementId: 'G-VZFTQB5EYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHUGrk7y2gYs8jT7paRKmUp3kmfQAk4pw',
    appId: '1:961803445314:android:4251a81fca8dd1e67b79db',
    messagingSenderId: '961803445314',
    projectId: 'presence-app-9a958',
    storageBucket: 'presence-app-9a958.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyJLEY-YpeL-UCESiE8eoQH1AqcxBa3aY',
    appId: '1:961803445314:ios:dd85c22b9b8ad2817b79db',
    messagingSenderId: '961803445314',
    projectId: 'presence-app-9a958',
    storageBucket: 'presence-app-9a958.firebasestorage.app',
    iosBundleId: 'com.rakafebriansy.presenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyJLEY-YpeL-UCESiE8eoQH1AqcxBa3aY',
    appId: '1:961803445314:ios:dd85c22b9b8ad2817b79db',
    messagingSenderId: '961803445314',
    projectId: 'presence-app-9a958',
    storageBucket: 'presence-app-9a958.firebasestorage.app',
    iosBundleId: 'com.rakafebriansy.presenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-zWDAntdsgS2H52W7TnGsGyg1CsvL0og',
    appId: '1:961803445314:web:93b6fb9c615bf6937b79db',
    messagingSenderId: '961803445314',
    projectId: 'presence-app-9a958',
    authDomain: 'presence-app-9a958.firebaseapp.com',
    storageBucket: 'presence-app-9a958.firebasestorage.app',
    measurementId: 'G-0FW5Y3EETE',
  );
}